services:
  postgres:
    container_name: "pgledger_postgres"
    image: "postgres:${POSTGRES_VERSION:-17.6}"
    command: >
      -c max_wal_size=2GB
    ports:
      - 5432:5432
    networks:
      - postgres-network
    environment:
      POSTGRES_USER: pgledger
      POSTGRES_PASSWORD: pgledger
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pgledger"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./psqlrc:/root/.psqlrc
      - .:/code

networks:
  postgres-network:
    driver: bridge
